export default Object.freeze({
  GET_REQUEST: 'LEADERS_GET_REQUEST',
  GET_SUCCESS: 'LEADERS_GET_SUCCESS',
  GET_FAILURE: 'LEADERS_GET_FAILURE',

  SET_WINNER: 'LEADERS_SET_WINNER',
  SET_WINNER_SUCCESS: 'LEADERS_SET_WINNER_SUCCESS',
  SET_WINNER_FAILURE: 'LEADERS_SET_WINNER_FAILURE',
});
