export default Object.freeze({
  GET_MODE_REQUEST: 'GAME_MODE_GET_REQUEST',
  GET_MODE_SUCCESS: 'GAME_MODE_GET_SUCCESS',
  GET_MODE_FAILURE: 'GAME_MODE_GET_FAILURE',

  SET_MODE: 'GAME_SET_MODE',

  SET_USER_NAME: 'GAME_SET_USER_NAME',

  SET_GRID: 'GAME_SET_GRID',

  CHECK_COL: 'GAME_CHECK_COL',

  INCREASE_COMPUTER_POINT: 'GAME_INCREASE_COMPUTER_POINT',

  INCREASE_USER_POINT: 'GAME_INCREASE_USER_POINT',

  CLEAR_STATE: 'GAME_CLEAR_STATE',
});
